use std::collections::HashMap;

use anyhow::Result;

use crate::core::types::{ProviderStatus, Report, Resource};

pub fn to_html(report: &Report) -> Result<String> {
    let resources_by_type = group_by_type(&report.resources);
    let attribution_breakdown = attribution_stats(&report.resources);

    let resource_sections = render_resource_sections(&resources_by_type);
    let attribution_rows = render_attribution_rows(&attribution_breakdown);
    let provider_rows = render_provider_rows(report);
    let summary_cards = render_summary_cards(report);

    let html = format!(
        r##"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>composit report — {workspace}</title>
<style>
:root {{
  --bg: #0d1117;
  --surface: #161b22;
  --border: #30363d;
  --text: #e6edf3;
  --text-muted: #7d8590;
  --accent: #58a6ff;
  --green: #3fb950;
  --yellow: #d29922;
  --red: #f85149;
  --orange: #db6d28;
}}
* {{ margin: 0; padding: 0; box-sizing: border-box; }}
body {{
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif;
  background: var(--bg);
  color: var(--text);
  line-height: 1.5;
  padding: 2rem;
  max-width: 1200px;
  margin: 0 auto;
}}
header {{
  border-bottom: 1px solid var(--border);
  padding-bottom: 1.5rem;
  margin-bottom: 2rem;
}}
header h1 {{
  font-size: 1.5rem;
  font-weight: 600;
  color: var(--accent);
}}
header h1 span {{ color: var(--text-muted); font-weight: 400; }}
.meta {{
  color: var(--text-muted);
  font-size: 0.85rem;
  margin-top: 0.5rem;
}}
.cards {{
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
  gap: 1rem;
  margin-bottom: 2rem;
}}
.card {{
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 8px;
  padding: 1.25rem;
}}
.card .label {{
  color: var(--text-muted);
  font-size: 0.8rem;
  text-transform: uppercase;
  letter-spacing: 0.05em;
}}
.card .value {{
  font-size: 1.75rem;
  font-weight: 600;
  margin-top: 0.25rem;
}}
.card .value.accent {{ color: var(--accent); }}
.card .value.yellow {{ color: var(--yellow); }}
.card .value.green {{ color: var(--green); }}
section {{
  margin-bottom: 2rem;
}}
section h2 {{
  font-size: 1.1rem;
  font-weight: 600;
  margin-bottom: 1rem;
  color: var(--text);
}}
section h2 .count {{
  color: var(--text-muted);
  font-weight: 400;
}}
table {{
  width: 100%;
  border-collapse: collapse;
  font-size: 0.85rem;
}}
th {{
  text-align: left;
  padding: 0.5rem 0.75rem;
  color: var(--text-muted);
  font-weight: 500;
  border-bottom: 1px solid var(--border);
  font-size: 0.8rem;
  text-transform: uppercase;
  letter-spacing: 0.05em;
}}
td {{
  padding: 0.5rem 0.75rem;
  border-bottom: 1px solid var(--border);
  vertical-align: top;
}}
tr:hover {{ background: rgba(88, 166, 255, 0.04); }}
.tag {{
  display: inline-block;
  padding: 0.15rem 0.5rem;
  border-radius: 12px;
  font-size: 0.75rem;
  font-weight: 500;
}}
.tag-human {{ background: rgba(63, 185, 80, 0.15); color: var(--green); }}
.tag-agent {{ background: rgba(210, 153, 34, 0.15); color: var(--yellow); }}
.tag-assisted {{ background: rgba(219, 109, 40, 0.15); color: var(--orange); }}
.tag-untracked {{ background: rgba(125, 133, 144, 0.15); color: var(--text-muted); }}
.tag-reachable {{ background: rgba(63, 185, 80, 0.15); color: var(--green); }}
.tag-unreachable {{ background: rgba(248, 81, 73, 0.15); color: var(--red); }}
.tag-unknown {{ background: rgba(210, 153, 34, 0.15); color: var(--yellow); }}
.mono {{ font-family: 'SF Mono', Consolas, monospace; font-size: 0.8rem; }}
.muted {{ color: var(--text-muted); }}
.detail {{ color: var(--text-muted); font-size: 0.8rem; }}
.two-col {{
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 1.5rem;
}}
@media (max-width: 768px) {{
  .two-col {{ grid-template-columns: 1fr; }}
  body {{ padding: 1rem; }}
}}
footer {{
  margin-top: 3rem;
  padding-top: 1rem;
  border-top: 1px solid var(--border);
  color: var(--text-muted);
  font-size: 0.8rem;
}}
footer a {{ color: var(--accent); text-decoration: none; }}
</style>
</head>
<body>

<header>
  <h1>composit <span>report</span></h1>
  <div class="meta">
    Workspace: <strong>{workspace}</strong> &middot;
    Generated: {generated} &middot;
    Scanner: v{version}
  </div>
</header>

{summary_cards}

{resource_sections}

<div class="two-col">
<section>
<h2>Attribution</h2>
<table>
<thead><tr><th>Author</th><th>Resources</th></tr></thead>
<tbody>
{attribution_rows}
</tbody>
</table>
</section>

{provider_section}
</div>

<footer>
  Generated by <a href="https://github.com/nuetzliches/composit">composit</a> v{version}
</footer>

</body>
</html>"##,
        workspace = html_escape(&report.workspace),
        generated = html_escape(&report.generated),
        version = html_escape(&report.scanner_version),
        summary_cards = summary_cards,
        resource_sections = resource_sections,
        attribution_rows = attribution_rows,
        provider_section = if report.providers.is_empty() {
            String::new()
        } else {
            format!(
                r#"<section>
<h2>Providers</h2>
<table>
<thead><tr><th>Name</th><th>Status</th><th>Capabilities</th></tr></thead>
<tbody>
{}
</tbody>
</table>
</section>"#,
                provider_rows
            )
        },
    );

    Ok(html)
}

fn group_by_type(resources: &[Resource]) -> Vec<(&str, Vec<&Resource>)> {
    let mut map: HashMap<&str, Vec<&Resource>> = HashMap::new();
    for r in resources {
        map.entry(&r.resource_type).or_default().push(r);
    }
    let mut result: Vec<_> = map.into_iter().collect();
    result.sort_by_key(|(t, _)| *t);
    result
}

fn attribution_stats(resources: &[Resource]) -> Vec<(String, String, usize)> {
    // (label, tag_class, count)
    let mut created_by: HashMap<String, usize> = HashMap::new();
    let mut assisted_by: HashMap<String, usize> = HashMap::new();
    let mut modified_by: HashMap<String, usize> = HashMap::new();
    let mut untracked = 0usize;

    for r in resources {
        match &r.created_by {
            Some(a) => *created_by.entry(a.clone()).or_insert(0) += 1,
            None => untracked += 1,
        }
        if let Some(agent) = r.extra.get("assisted_by").and_then(|v| v.as_str()) {
            *assisted_by.entry(agent.to_string()).or_insert(0) += 1;
        }
        if let Some(lm) = r.extra.get("last_modified_by").and_then(|v| v.as_str()) {
            if lm.starts_with("agent:") {
                *modified_by.entry(lm.to_string()).or_insert(0) += 1;
            }
        }
    }

    let mut result: Vec<(String, String, usize)> = Vec::new();

    // Agent modifiers first (most important signal)
    let mut mods: Vec<_> = modified_by.into_iter().collect();
    mods.sort_by_key(|b| std::cmp::Reverse(b.1));
    for (author, count) in mods {
        result.push((
            format!("{} (last modified)", author),
            "tag-agent".to_string(),
            count,
        ));
    }

    // Agent assistants
    let mut assists: Vec<_> = assisted_by.into_iter().collect();
    assists.sort_by_key(|b| std::cmp::Reverse(b.1));
    for (agent, count) in assists {
        result.push((
            format!("{} (co-authored)", agent),
            "tag-assisted".to_string(),
            count,
        ));
    }

    // Then creators
    let mut creators: Vec<_> = created_by.into_iter().collect();
    creators.sort_by_key(|b| std::cmp::Reverse(b.1));
    for (author, count) in creators {
        let tag = if author.starts_with("agent:") {
            "tag-agent"
        } else {
            "tag-human"
        };
        result.push((format!("{} (created)", author), tag.to_string(), count));
    }

    if untracked > 0 {
        result.push((
            "untracked".to_string(),
            "tag-untracked".to_string(),
            untracked,
        ));
    }
    result
}

fn render_summary_cards(report: &Report) -> String {
    let agent_modified = report
        .resources
        .iter()
        .filter(|r| {
            r.extra
                .get("last_modified_by")
                .and_then(|v| v.as_str())
                .is_some_and(|lm| lm.starts_with("agent:"))
        })
        .count();

    let mut cards = vec![format!(
        r#"<div class="card"><div class="label">Resources</div><div class="value accent">{}</div></div>"#,
        report.summary.total_resources
    )];

    if report.summary.agent_created > 0 {
        cards.push(format!(
            r#"<div class="card"><div class="label">Agent-created</div><div class="value yellow">{}</div></div>"#,
            report.summary.agent_created
        ));
    }

    if report.summary.agent_assisted > 0 {
        cards.push(format!(
            r#"<div class="card"><div class="label">Agent-assisted</div><div class="value" style="color: var(--orange)">{}</div></div>"#,
            report.summary.agent_assisted
        ));
    }

    if agent_modified > 0 {
        cards.push(format!(
            r#"<div class="card"><div class="label">Agent-modified</div><div class="value yellow">{}</div></div>"#,
            agent_modified
        ));
    }

    cards.push(format!(
        r#"<div class="card"><div class="label">Human-created</div><div class="value green">{}</div></div>"#,
        report.summary.human_created
    ));

    if report.summary.auto_detected > 0 {
        cards.push(format!(
            r#"<div class="card"><div class="label">Untracked</div><div class="value">{}</div></div>"#,
            report.summary.auto_detected
        ));
    }

    if report.summary.providers > 0 {
        cards.push(format!(
            r#"<div class="card"><div class="label">Providers</div><div class="value">{}</div></div>"#,
            report.summary.providers
        ));
    }

    if report.summary.estimated_monthly_cost != "0 EUR" {
        cards.push(format!(
            r#"<div class="card"><div class="label">Est. Monthly Cost</div><div class="value accent">{}</div></div>"#,
            html_escape(&report.summary.estimated_monthly_cost)
        ));
    }

    format!(r#"<div class="cards">{}</div>"#, cards.join("\n"))
}

fn render_resource_sections(groups: &[(&str, Vec<&Resource>)]) -> String {
    let mut sections = Vec::new();

    for (resource_type, resources) in groups {
        let rows: Vec<String> = resources
            .iter()
            .map(|r| {
                let name_or_path = r
                    .name
                    .as_deref()
                    .or(r.path.as_deref())
                    .unwrap_or("-");

                let is_assisted = r
                    .extra
                    .get("agent_assisted")
                    .and_then(|v| v.as_bool())
                    .unwrap_or(false);
                let assisted_by = r
                    .extra
                    .get("assisted_by")
                    .and_then(|v| v.as_str())
                    .unwrap_or("");

                let attribution = match &r.created_by {
                    Some(a) if a.starts_with("agent:") => {
                        format!(r#"<span class="tag tag-agent">{}</span>"#, html_escape(a))
                    }
                    Some(a) if a.starts_with("human:") && is_assisted => {
                        format!(
                            r#"<span class="tag tag-human">{}</span> <span class="tag tag-assisted">{}</span>"#,
                            html_escape(a),
                            html_escape(assisted_by)
                        )
                    }
                    Some(a) if a.starts_with("human:") => {
                        format!(r#"<span class="tag tag-human">{}</span>"#, html_escape(a))
                    }
                    _ => r#"<span class="tag tag-untracked">untracked</span>"#.to_string(),
                };

                let date = r.created.as_deref().unwrap_or("");

                // Last modified by
                let last_mod = r.extra.get("last_modified_by").and_then(|v| v.as_str());
                let last_mod_html = match last_mod {
                    Some(lm) if lm.starts_with("agent:") => {
                        format!(r#"<span class="tag tag-agent">{}</span>"#, html_escape(lm))
                    }
                    Some(lm) if lm.starts_with("human:") => {
                        format!(r#"<span class="tag tag-human">{}</span>"#, html_escape(lm))
                    }
                    _ => String::new(),
                };

                let details = format_details(r);

                format!(
                    r#"<tr>
  <td class="mono">{}</td>
  <td>{}</td>
  <td>{}</td>
  <td class="muted">{}</td>
  <td class="detail">{}</td>
</tr>"#,
                    html_escape(name_or_path),
                    attribution,
                    last_mod_html,
                    date,
                    details
                )
            })
            .collect();

        sections.push(format!(
            r#"<section>
<h2>{} <span class="count">({})</span></h2>
<table>
<thead><tr><th>Name / Path</th><th>Created by</th><th>Last modified</th><th>Date</th><th>Details</th></tr></thead>
<tbody>
{}
</tbody>
</table>
</section>"#,
            html_escape(resource_type),
            resources.len(),
            rows.join("\n")
        ));
    }

    sections.join("\n")
}

fn render_attribution_rows(stats: &[(String, String, usize)]) -> String {
    stats
        .iter()
        .map(|(label, tag_class, count)| {
            format!(
                r#"<tr><td><span class="tag {}">{}</span></td><td>{}</td></tr>"#,
                tag_class,
                html_escape(label),
                count
            )
        })
        .collect::<Vec<_>>()
        .join("\n")
}

fn render_provider_rows(report: &Report) -> String {
    report
        .providers
        .iter()
        .map(|p| {
            let (status_class, status_text) = match p.status {
                ProviderStatus::Reachable => ("tag-reachable", "reachable"),
                ProviderStatus::Unreachable => ("tag-unreachable", "unreachable"),
                ProviderStatus::Unknown => ("tag-unknown", "unknown"),
            };
            let caps = if p.capabilities.is_empty() {
                "-".to_string()
            } else {
                p.capabilities.join(", ")
            };
            format!(
                r#"<tr><td class="mono">{}</td><td><span class="tag {}">{}</span></td><td>{}</td></tr>"#,
                html_escape(&p.name),
                status_class,
                status_text,
                html_escape(&caps)
            )
        })
        .collect::<Vec<_>>()
        .join("\n")
}

fn format_details(r: &Resource) -> String {
    let mut parts = Vec::new();

    if let Some(services) = r.extra.get("services").and_then(|v| v.as_u64()) {
        parts.push(format!("{} services", services));
    }
    if let Some(image) = r.extra.get("image").and_then(|v| v.as_str()) {
        parts.push(format!("<code>{}</code>", html_escape(image)));
    }
    if let Some(build) = r.extra.get("build").and_then(|v| v.as_str()) {
        parts.push(format!("build: <code>{}</code>", html_escape(build)));
    }
    if let Some(ports) = r.extra.get("ports").and_then(|v| v.as_array()) {
        let port_strs: Vec<&str> = ports.iter().filter_map(|p| p.as_str()).collect();
        if !port_strs.is_empty() {
            parts.push(format!("ports: {}", port_strs.join(", ")));
        }
    }
    if let Some(vars) = r.extra.get("variables").and_then(|v| v.as_u64()) {
        parts.push(format!("{} variables", vars));
    }
    if let Some(schedule) = r.extra.get("schedule").and_then(|v| v.as_str()) {
        parts.push(format!("<code>{}</code>", html_escape(schedule)));
    }
    if let Some(managed) = r.extra.get("managed_resources").and_then(|v| v.as_u64()) {
        if managed > 0 {
            parts.push(format!("{} managed resources", managed));
        }
    }
    if let Some(compose) = r.extra.get("compose_file").and_then(|v| v.as_str()) {
        // Only show for services (not compose files themselves)
        if r.resource_type == "docker_service" {
            parts.push(format!("in <code>{}</code>", html_escape(compose)));
        }
    }
    // Terraform config summary
    if let Some(res) = r.extra.get("resources").and_then(|v| v.as_u64()) {
        if res > 0 {
            parts.push(format!("{} resources", res));
        }
    }
    if let Some(mods) = r.extra.get("modules").and_then(|v| v.as_u64()) {
        if mods > 0 {
            parts.push(format!("{} modules", mods));
        }
    }
    if let Some(outputs) = r.extra.get("outputs").and_then(|v| v.as_u64()) {
        if outputs > 0 {
            parts.push(format!("{} outputs", outputs));
        }
    }
    if let Some(providers) = r.extra.get("provider_list").and_then(|v| v.as_array()) {
        let prov_strs: Vec<&str> = providers.iter().filter_map(|p| p.as_str()).collect();
        if !prov_strs.is_empty() {
            parts.push(format!("providers: {}", prov_strs.join(", ")));
        }
    }
    // Terraform resource type
    if let Some(rt) = r.extra.get("resource_type").and_then(|v| v.as_str()) {
        parts.push(format!("<code>{}</code>", html_escape(rt)));
    }
    // Terraform module source
    if let Some(source) = r.extra.get("source").and_then(|v| v.as_str()) {
        parts.push(format!("<code>{}</code>", html_escape(source)));
    }
    if let Some(version) = r.extra.get("version").and_then(|v| v.as_str()) {
        parts.push(format!("v{}", html_escape(version)));
    }
    // Caddyfile
    if let Some(sites) = r.extra.get("sites").and_then(|v| v.as_u64()) {
        parts.push(format!("{} sites", sites));
    }
    if let Some(domains) = r.extra.get("domains").and_then(|v| v.as_array()) {
        let dom_strs: Vec<&str> = domains.iter().filter_map(|d| d.as_str()).collect();
        if !dom_strs.is_empty() {
            parts.push(
                dom_strs
                    .iter()
                    .map(|d| html_escape(d))
                    .collect::<Vec<_>>()
                    .join(", "),
            );
        }
    }
    if let Some(rp) = r.extra.get("reverse_proxy").and_then(|v| v.as_str()) {
        parts.push(format!("&rarr; <code>{}</code>", html_escape(rp)));
    }
    if r.extra
        .get("file_server")
        .and_then(|v| v.as_bool())
        .unwrap_or(false)
    {
        parts.push("file_server".to_string());
    }
    // Workflows
    if let Some(platform) = r.extra.get("platform").and_then(|v| v.as_str()) {
        parts.push(html_escape(platform));
    }
    if let Some(triggers) = r.extra.get("triggers").and_then(|v| v.as_array()) {
        let trig_strs: Vec<&str> = triggers.iter().filter_map(|t| t.as_str()).collect();
        if !trig_strs.is_empty() {
            parts.push(format!("on: {}", trig_strs.join(", ")));
        }
    }
    if let Some(jobs) = r.extra.get("jobs").and_then(|v| v.as_u64()) {
        if jobs > 0 && r.resource_type == "workflow" {
            parts.push(format!("{} jobs", jobs));
        }
    }
    if let Some(runner) = r.extra.get("runs_on").and_then(|v| v.as_str()) {
        parts.push(format!("runner: <code>{}</code>", html_escape(runner)));
    }
    // Prometheus
    if let Some(sc) = r.extra.get("scrape_configs").and_then(|v| v.as_u64()) {
        parts.push(format!("{} scrape configs", sc));
    }
    if let Some(job_names) = r.extra.get("job_names").and_then(|v| v.as_array()) {
        let names: Vec<&str> = job_names.iter().filter_map(|j| j.as_str()).collect();
        if !names.is_empty() {
            parts.push(format!("jobs: {}", names.join(", ")));
        }
    }
    if let Some(rules) = r.extra.get("rules").and_then(|v| v.as_u64()) {
        parts.push(format!("{} rules", rules));
    }
    if let Some(groups) = r.extra.get("groups").and_then(|v| v.as_u64()) {
        if groups > 0 && r.resource_type == "prometheus_rules" {
            parts.push(format!("{} groups", groups));
        }
    }
    if r.extra
        .get("alerting")
        .and_then(|v| v.as_bool())
        .unwrap_or(false)
    {
        parts.push("alerting".to_string());
    }

    parts.join(" &middot; ")
}

fn html_escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}
