use std::collections::HashMap;
use std::path::Path;

use anyhow::Result;
use colored::Colorize;

use crate::core::types::Report;

/// Header prepended to every generated Compositfile. Without this, coding
/// agents tend to auto-update the Compositfile whenever they add
/// infrastructure — which silently closes the drift loop the file exists
/// to expose. The notice is addressed to agents reading the file as
/// context; humans editing directly can ignore it.
const AGENT_HEADER: &str = "\
# Compositfile — reviewed SHOULD-state of this workspace.
#
# AGENT INSTRUCTIONS: Do not modify this file unless the user explicitly
# asks. This file is human-reviewed governance. When you change the
# repo's infrastructure (docker-compose, workflows, terraform, env
# files), leave this file alone — `composit diff` will surface the drift
# for the user to decide whether the Compositfile should follow.
# Silently updating the Compositfile defeats its purpose.

";

pub fn run_init(dir: &Path, workspace_name: Option<String>, report: Option<&Report>) -> Result<()> {
    let workspace = workspace_name.unwrap_or_else(|| workspace_from_dir(dir));

    let content = match report {
        Some(r) => generate_from_report(&workspace, r),
        None => generate_minimal(&workspace),
    };

    let compositfile_path = dir.join("Compositfile");
    std::fs::write(&compositfile_path, &content)?;

    let display_path = std::env::current_dir()
        .ok()
        .and_then(|cwd| {
            compositfile_path
                .strip_prefix(&cwd)
                .ok()
                .map(|p| p.to_path_buf())
        })
        .unwrap_or_else(|| compositfile_path.clone());

    println!();
    println!(
        "  {} {}",
        "Compositfile written:".green().bold(),
        display_path.display()
    );
    if report.is_some() {
        // composit init also writes composit-report.yaml when a scan ran
        // (main.rs handles the actual write); surface it so the user knows
        // `composit diff` will find it without an extra scan step.
        let report_path = dir.join("composit-report.yaml");
        let display_report = std::env::current_dir()
            .ok()
            .and_then(|cwd| {
                report_path
                    .strip_prefix(&cwd)
                    .ok()
                    .map(|p| p.to_path_buf())
            })
            .unwrap_or(report_path);
        println!(
            "  {}         {}",
            "Scan report:".green().bold(),
            display_report.display()
        );
    }
    println!("  {} {}", "Workspace:".dimmed(), workspace.bold());
    if let Some(r) = report {
        println!(
            "  {} {} resources, {} providers",
            "Seeded from scan:".dimmed(),
            r.summary.total_resources,
            r.summary.providers
        );
    }
    println!();
    println!(
        "  {}  {}",
        "composit diff".bold(),
        "— check for governance violations".dimmed()
    );
    println!();

    Ok(())
}

fn workspace_from_dir(dir: &Path) -> String {
    // Try git remote "origin" URL → extract repo name
    if let Ok(output) = std::process::Command::new("git")
        .args(["-C", &dir.to_string_lossy(), "remote", "get-url", "origin"])
        .output()
    {
        if output.status.success() {
            let url = String::from_utf8_lossy(&output.stdout).trim().to_string();
            if let Some(name) = repo_name_from_url(&url) {
                return name;
            }
        }
    }
    dir.file_name()
        .map(|n| n.to_string_lossy().to_string())
        .unwrap_or_else(|| "workspace".to_string())
}

fn repo_name_from_url(url: &str) -> Option<String> {
    // Handles:
    //   https://github.com/org/repo.git  →  repo
    //   git@github.com:org/repo.git      →  repo
    let name = url
        .trim_end_matches('/')
        .trim_end_matches(".git")
        .rsplit('/')
        .next()?
        .to_string();
    if name.is_empty() {
        None
    } else {
        Some(name)
    }
}

fn generate_minimal(workspace: &str) -> String {
    format!(
        r#"{AGENT_HEADER}workspace "{workspace}" {{

  scan {{
    exclude = []
  }}

  resources {{
    # max_total = 200

    # allow "workflow" {{
    #   max = 10
    # }}
  }}
}}
"#
    )
}

fn generate_from_report(workspace: &str, report: &Report) -> String {
    let mut out = String::new();

    out.push_str(AGENT_HEADER);
    out.push_str(&format!(
        "# Generated by composit init — {}\n",
        chrono::Utc::now().format("%Y-%m-%d")
    ));
    out.push_str("# Review and adjust constraints to match your governance requirements.\n\n");
    out.push_str(&format!("workspace \"{workspace}\" {{\n"));

    // Providers
    if !report.providers.is_empty() {
        out.push_str("\n  # --- Providers ---\n");
        out.push_str("  # Discovered during scan. Set trust = \"contract\" and add an\n");
        out.push_str("  # auth block for providers that require authentication.\n\n");

        for provider in &report.providers {
            let label = provider
                .name
                .to_lowercase()
                .replace(|c: char| !c.is_alphanumeric() && c != '-', "-");
            let manifest = format!(
                "{}/.well-known/composit.json",
                provider.endpoint.trim_end_matches('/')
            );

            out.push_str(&format!("  provider \"{label}\" {{\n"));
            out.push_str(&format!("    manifest = \"{manifest}\"\n"));
            out.push_str("    trust    = \"public\"\n");
            if !provider.capabilities.is_empty() {
                out.push_str(&format!(
                    "    # capabilities: {}\n",
                    provider.capabilities.join(", ")
                ));
            }
            out.push_str("    # compliance = []\n");
            out.push_str("    # auth {\n");
            out.push_str("    #   type = \"api-key\"\n");
            out.push_str("    #   env  = \"PROVIDER_API_KEY\"\n");
            out.push_str("    # }\n");
            out.push_str("  }\n\n");
        }
    }

    // Resources
    if !report.resources.is_empty() {
        let mut by_type: HashMap<&str, usize> = HashMap::new();
        for r in &report.resources {
            *by_type.entry(r.resource_type.as_str()).or_insert(0) += 1;
        }

        let total = report.summary.total_resources;
        // 20% headroom, minimum +10
        let max_total = std::cmp::max(total + 10, (total as f64 * 1.2).ceil() as usize);

        out.push_str("  # --- Resource Constraints ---\n");
        out.push_str("  # Seeded from scan. max values include headroom — tighten as needed.\n");
        out.push_str("  # With allow blocks present, unlisted types become violations.\n\n");
        out.push_str("  resources {\n");
        out.push_str(&format!("    max_total = {max_total}\n\n"));

        let mut types: Vec<(&str, usize)> = by_type.into_iter().collect();
        types.sort_by(|a, b| b.1.cmp(&a.1).then(a.0.cmp(b.0)));

        for (resource_type, count) in &types {
            // 2× headroom, minimum count+5
            let max = std::cmp::max(count + 5, count * 2);
            out.push_str(&format!("    allow \"{resource_type}\" {{\n"));
            out.push_str(&format!("      max = {max}  # found: {count}\n"));
            out.push_str("    }\n");
        }

        out.push_str("  }\n");
    }

    out.push_str("}\n");
    out
}
