pub mod agent_spec;
pub mod ansible;
pub mod caddyfile;
pub mod cargo_manifest;
pub mod cron;
pub mod db_migrations;
pub mod deploy_scripts;
pub mod docker;
pub mod env_files;
pub mod extra_patterns;
pub mod fly_toml;
pub mod go_module;
pub mod grafana;
pub mod kubernetes;
pub mod mcp_config;
pub mod mcp_provider;
pub mod nginx;
pub mod opa_policy;
pub mod prometheus;
pub mod proto;
pub mod render_yaml;
pub mod skaffold;
pub mod tempo;
pub mod terraform;
pub mod traefik;
pub mod vercel_json;
pub mod workflows;

use crate::core::registry::ScannerRegistry;

pub fn register_default_scanners(registry: &mut ScannerRegistry) {
    registry.register(Box::new(docker::DockerScanner));
    registry.register(Box::new(env_files::EnvFilesScanner));
    registry.register(Box::new(terraform::TerraformScanner));
    registry.register(Box::new(caddyfile::CaddyfileScanner));
    registry.register(Box::new(nginx::NginxScanner));
    registry.register(Box::new(workflows::WorkflowScanner));
    registry.register(Box::new(prometheus::PrometheusScanner));
    registry.register(Box::new(grafana::GrafanaScanner));
    registry.register(Box::new(cron::CronScanner));
    registry.register(Box::new(kubernetes::KubernetesScanner));
    registry.register(Box::new(opa_policy::OpaPolicyScanner));
    registry.register(Box::new(mcp_config::McpConfigScanner));
    registry.register(Box::new(mcp_provider::McpProviderScanner));
    registry.register(Box::new(fly_toml::FlyTomlScanner));
    registry.register(Box::new(render_yaml::RenderYamlScanner));
    registry.register(Box::new(vercel_json::VercelJsonScanner));
    registry.register(Box::new(skaffold::SkaffoldScanner));
    registry.register(Box::new(traefik::TraefikScanner));
    registry.register(Box::new(proto::ProtoScanner));
    registry.register(Box::new(tempo::TempoScanner));
    registry.register(Box::new(db_migrations::DbMigrationsScanner));
    registry.register(Box::new(deploy_scripts::DeployScriptsScanner));
    registry.register(Box::new(ansible::AnsibleScanner));
    registry.register(Box::new(agent_spec::AgentSpecScanner));
    registry.register(Box::new(cargo_manifest::CargoManifestScanner));
    registry.register(Box::new(go_module::GoModuleScanner));
}
